# SPDX-FileCopyrightText: 2025 ORDeC contributors
# SPDX-License-Identifier: Apache-2.0

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - npm
    - graphviz

sphinx:
   configuration: docs/conf.py
  
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
    
