name: run pytest
on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tub-msc/ordec-base:sha-1a0c5bc
      options: --user root
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: Source venv
        run: |
          . /home/app/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Add ngspice to path
        run: |
          echo PATH=$PATH:/home/app/ngspice/min/bin >> $GITHUB_ENV
      - name: pip install
        run: pip install -e .
      - name: run tests
        run: COVERAGE_FILE=/tmp/coverage pytest --cov-report=html:/tmp/htmlcov -o cache_dir=/tmp/pytestcache --junit-xml=/tmp/test-results.xml
      - name: display test results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: /tmp/test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
